name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.location }}
        username: ubuntu
        key: ${{ secrets.cse312 }}
        port: 22
        source: "."
        target: "/home/ubuntu/"

    - name: SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.location }}
        username: your-ec2-user
        key: ${{ secrets.cse312 }}
        port: 22
        script: |
          kill $(cat server.pid)
          rm -f server.pid
          cd /home/ubuntu/404-BrainNotFound
          nohup python server.py & echo $! > server.pid
          
          
          
